import json
import os
import time
from io import BytesIO
from pathlib import Path

import httpx
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas


def main() -> None:
    signing_api_url = os.getenv("SIGNING_API_URL", "http://localhost:8000")
    output_path = Path(
        os.getenv("SIGNED_OUTPUT_PATH", "artifacts/signed-demo.pdf")
    )
    input_path = Path(os.getenv("DEMO_INPUT_PDF", "samples/input.pdf"))

    wait_for_ready(signing_api_url)
    pdf_bytes = read_or_generate_pdf(input_path)
    metadata = {
        "field_name": "Signature1",
        "reason": "Demo CSC signing",
        "location": "Demo container",
        "stamp": {
            "text": "CSC demo stamp %(ts)s",
            "page": 0,
            "x": 72,
            "y": 72,
            "width": 240,
            "height": 56,
        },
    }

    with httpx.Client(timeout=300) as client:
        response = client.post(
            f"{signing_api_url}/v1/sign/pdf",
            files={"pdf": ("input.pdf", pdf_bytes, "application/pdf")},
            data={"metadata": json.dumps(metadata)},
        )
        response.raise_for_status()

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_bytes(response.content)
    print(f"Wrote signed PDF to {output_path}")


def wait_for_ready(signing_api_url: str, timeout_seconds: int = 120) -> None:
    deadline = time.monotonic() + timeout_seconds
    while time.monotonic() < deadline:
        try:
            response = httpx.get(f"{signing_api_url}/readyz", timeout=5)
            if response.status_code == 200:
                return
        except httpx.HTTPError:
            pass
        time.sleep(2)
    raise RuntimeError("signing-api did not become ready in time")


def read_or_generate_pdf(input_path: Path) -> bytes:
    if input_path.exists():
        return input_path.read_bytes()
    return generate_sample_pdf()


def generate_sample_pdf() -> bytes:
    output = BytesIO()
    pdf = canvas.Canvas(output, pagesize=A4)
    width, height = A4
    pdf.setFont("Helvetica-Bold", 18)
    pdf.drawString(72, height - 96, "CSC signing demo")
    pdf.setFont("Helvetica", 11)
    pdf.drawString(72, height - 128, "Generated by the demo-client container.")
    pdf.drawString(72, height - 148, "This PDF will be signed by signing-api.")
    pdf.showPage()
    pdf.save()
    return output.getvalue()


if __name__ == "__main__":
    main()
